#!/bin/bash
set -euo pipefail

# G5 full unified context graph on every evaluation dataset at 4K context.
#
# Usage:
#   bash scripts/submit_ucm_graph_g5_full_4k.sh [--dry-run]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_SLURM="${SCRIPT_DIR}/submit_ucm_a800.slurm"
RUN_SHORT_NAME="G5_F1_unified_context_graph_full_all_4k"
DRY_RUN=0

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
  shift
fi
if [[ "$#" -ne 0 ]]; then
  echo "Usage: $0 [--dry-run]" >&2
  exit 2
fi

GENERATOR_MAX_CONTEXT_LENGTH=4096
GENERATOR_MAX_CROSSFILE_LENGTH=3072
if [[ "${GENERATOR_MAX_CONTEXT_LENGTH}" != "4096" || "${GENERATOR_MAX_CROSSFILE_LENGTH}" != "3072" ]]; then
  echo "G5 experiments require the fixed 4K/3K+1K context allocation." >&2
  exit 2
fi

EXPORTS=(
  "RUN_MODE=ucm_full"
  "RUN_SHORT_NAME=${RUN_SHORT_NAME}"
  "EVAL_DATASETS=github_eval:cceval_python:cceval_java:repoeval_line:repoeval_api"
  "GENERATOR_MAX_CONTEXT_LENGTH=${GENERATOR_MAX_CONTEXT_LENGTH}"
  "GENERATOR_MAX_CROSSFILE_LENGTH=${GENERATOR_MAX_CROSSFILE_LENGTH}"
  "GENERATOR_MAX_GENERATION_LENGTH=64"
  "GENERATOR_BATCH_SIZE_PER_GPU=8"
  "RETRIEVER_QUERY_CONTEXT_LENGTH=256"
  "RETRIEVER_CANDIDATE_CONTEXT_LENGTH=512"
  "RETRIEVER_BATCH_SIZE_PER_GPU=32"
  "SAMPLE_NUMBER=10"
  "UCM_BASE_TOPK=60"
  "UCM_TOPK_PER_PATH=30"
  "UCM_PATH_TOPK=5"
  "UCM_CANDIDATE_POOL_SIZE=140"
  "UCM_DISABLE_IDENTIFIER_QUERY=0"
  "UCM_DISABLE_IMPORT_API_QUERY=0"
  "UCM_ENABLE_PATH_QUERY=0"
  "UCM_DISABLE_ENHANCED_BM25=0"
  "UCM_ENABLE_CONTEXT_GATE=0"
  "UCM_ENABLE_CONTEXT_GRAPH=1"
  "UCM_GRAPH_MAX_SEED=20"
  "UCM_GRAPH_MAX_NEIGHBORS_PER_SEED=3"
  "UCM_GRAPH_MAX_EXPANDED=40"
  "UCM_GRAPH_ENABLE_SAME_FILE_EDGES=1"
  "UCM_GRAPH_ENABLE_IDENTIFIER_EDGES=1"
  "UCM_GRAPH_ENABLE_IMPORT_EDGES=1"
  "UCM_GRAPH_ENABLE_API_CALL_EDGES=1"
  "UCM_GRAPH_IDENTIFIER_QUERY_ONLY=1"
  "UCM_GRAPH_API_CALL_QUERY_ONLY=1"
  "UCM_GRAPH_IDENTIFIER_MAX_DF=12"
  "UCM_GRAPH_API_CALL_MAX_DF=12"
  "UCM_GRAPH_ENABLE_TYPED_DEPENDENCY_EDGES=0"
  "UCM_GRAPH_ENABLE_UNIFIED_CONTEXT_EDGES=1"
  "UCM_GRAPH_ENABLE_MULTI_EVIDENCE=1"
  "UCM_GRAPH_UNIFIED_QUERY_MAX=16"
  "UCM_GRAPH_UNIFIED_QUERY_CONTEXT_LINES=160"
  "UCM_GRAPH_UNIFIED_MAX_DF=12"
  "UCM_GRAPH_MAX_EVIDENCE_PER_CANDIDATE=12"
  "UCM_GRAPH_UNIFIED_RECEIVER_WEIGHT=3.2"
  "UCM_GRAPH_UNIFIED_OVERRIDE_WEIGHT=2.9"
  "UCM_GRAPH_UNIFIED_MEMBER_WEIGHT=2.6"
  "UCM_GRAPH_UNIFIED_IMPORT_WEIGHT=2.5"
  "UCM_GRAPH_UNIFIED_INHERITANCE_WEIGHT=2.3"
  "UCM_GRAPH_UNIFIED_SIGNATURE_WEIGHT=1.7"
  "UCM_GRAPH_UNIFIED_CONTROL_WEIGHT=0.8"
  "UCM_GRAPH_TYPED_CALL_WEIGHT=1.8"
  "UCM_GRAPH_TYPED_TYPE_WEIGHT=2.0"
  "UCM_GRAPH_TYPED_DEF_USE_WEIGHT=1.4"
  "UCM_GRAPH_TYPED_ALLOW_TARGET_FILE=0"
  "UCM_GRAPH_SEED_RANK_DECAY=0.05"
  "UCM_GRAPH_DISTANCE_DECAY=0.75"
  "UCM_GRAPH_SAME_FILE_WEIGHT=1.0"
  "UCM_GRAPH_IDENTIFIER_WEIGHT=1.2"
  "UCM_GRAPH_IMPORT_WEIGHT=1.4"
  "UCM_GRAPH_API_CALL_WEIGHT=1.6"
  "UCM_GRAPH_QUERY_OVERLAP_BONUS=2"
  "UCM_GRAPH_QUERY_API_BONUS=2"
  "UCM_GRAPH_MAX_SELECTED=2"
  "UCM_GRAPH_MAX_SELECTED_TOKENS=768"
  "UCM_GRAPH_SHOW_RELATIONS_IN_PROMPT=0"
  "UCM_GRAPH_SHOW_HIGH_CONFIDENCE_PATHS=1"
  "UCM_GRAPH_PROMPT_MIN_CONFIDENCE=3.0"
  "UCM_GRAPH_ENABLE_RERANK=1"
  "UCM_GRAPH_ENABLE_PATH_RERANK=1"
  "UCM_GRAPH_RERANK_ALPHA=0.03"
  "UCM_GRAPH_PATH_SCORE_SCALE=4.0"
  "UCM_GRAPH_PATH_MULTI_RELATION_BONUS=0.004"
  "UCM_GRAPH_PATH_QUERY_ORIGIN_BONUS=0.003"
  "UCM_GRAPH_ENABLE_EVIDENCE_GATE=1"
  "UCM_GRAPH_NEW_CANDIDATE_MIN_PATHS=2"
  "UCM_GRAPH_NEW_CANDIDATE_MIN_CONFIDENCE=3.0"
  "UCM_GRAPH_SOURCE_PRIOR_SAME_FILE=0"
  "UCM_GRAPH_SOURCE_PRIOR_IDENTIFIER=0"
  "UCM_GRAPH_SOURCE_PRIOR_IMPORT=0"
  "UCM_GRAPH_SOURCE_PRIOR_API_CALL=0"
  "UCM_GRAPH_DISTANCE_PENALTY=0.002"
  "UCM_TRACE_OVERWRITE=1"
)

join_by_comma() {
  local IFS=","
  echo "$*"
}

EXPORT_STRING="$(join_by_comma "${EXPORTS[@]}")"
echo "G5 full unified graph"
echo "  run=${RUN_SHORT_NAME}"
echo "  datasets=github_eval,cceval_python,cceval_java,repoeval_line,repoeval_api"
echo "  context=4096 crossfile=3072 infile=1024"
echo "  graph=same-file,identifier,import,api-call,typed,member,inheritance,override,signature,visible-PDG/CFG"

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "  sbatch --export=ALL,<g5-full-config> ${BASE_SLURM}"
else
  sbatch --export="ALL,${EXPORT_STRING}" "${BASE_SLURM}"
fi
